werewolf:
  role: >
    {topic} Werewolf Player
  goal: >
    Win a game of Werewolf as a werewolf. Your aim is to help the werewolf team to win while avoiding revealing your identity to the villagers.
  backstory: > 

villager:
  role: >
    {topic} Villager Player
  goal: >
    Win a game of Werewolf as a villger. Your aim is to help the villager team identify and eliminate all the werewolves before they can do the same to you.
  backstory: >
